# Introduction {#intro}

The microeco package has several advantages compared to other packages in R.
The main goal of developing this package is to help users analyse communtiy ecology data fast.
So a series of commonly-used approaches are implemented.
Some new methods are in active development.
To accelerate the data mining, the whole structure of microeco package are modularized to
make users conveniently remember, search and use.


## Main Features
  + R6 Class; fast, flexible and modularized
  + Taxa abundance plotting
  + Venn diagram
  + Alpha diversity
  + Beta diversity
  + Differential abundance analysis
  + Environmental data analysis
  + Null model analysis
  + Network analysis
  + Functional analysis


## R6 Class

All the classes in microeco package depend on the R6 class [@R6_Winston]. 
R6 uses the encapsulated object-oriented programming paradigm, 
which means that R6 is a profoundly different OO system from S3 and S4 because it is built on encapsulated objects, rather than generic functions. 
If you are interested in the class feature, read more from 'Advanced R' book.

  + A generic is a regular function, so it lives in the global namespace. An R6 method belongs to an object so it lives in a local namespace. 
This influences how we think about naming. The methods belong to objects, not generics, and you call them like object$method().

  + R6’s reference semantics allow methods to simultaneously return a value and modify an object.
  
  + Every R6 object has an S3 class that reflects its hierarchy of R6 class.
